databases:
  - name: metering-db
    databaseName: metering
    plan: free

services:
  - type: web
    name: brunata-metering-demo
    runtime: native
    plan: free
    region: frankfurt
    buildCommand: mvn -q -DskipTests -pl app -am package
    startCommand: >-
      bash -lc 'export SPRING_DATASOURCE_URL=$(echo "$DATABASE_URL" | sed -E "s/^postgres:/jdbc:postgresql:/");
      java -jar app/target/app-0.1.0.jar --server.port=$PORT'
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: DATABASE_URL
        fromDatabase:
          name: metering-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: metering-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: metering-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate
      - key: SERVER_FORWARD_HEADERS_STRATEGY
        value: framework
    healthCheckPath: /actuator/health
    autoDeploy: true
