spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/metering
    username: metering
    password: metering
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-components: always
      show-details: always
  
server:
  address: 0.0.0.0
  port: 8080

# Reverse-Proxy/Header-Erkennung (Render, nginx, etc.)
server.forward-headers-strategy: framework

billing:
  scale: 2
  roundingMode: HALF_UP

integration:
  enabled: true
  offlineHours: 24
  jiraBaseUrl: http://localhost:8081
  erpBaseUrl: http://localhost:8082

# Beispiel (optional) für Jasypt-verschlüsselte Properties. Setze JASYPT_ENCRYPTOR_PASSWORD als Env.
# integration:
#   apiToken: "ENC(<verschlüsselter-token>)"
